FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libnl-3-dev \
    libnl-genl-3-dev \
    iproute2 \
    iw \
    wireless-tools \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /openCAPWAP
COPY . .
RUN mkdir -p /var/log
CMD ["/bin/bash", "/openCAPWAP/start_wtp_clean.sh"]
